# Config related with Sup.
[sup]
# Path to an unix socket, to which Sup daemon will be listening.
socket = "./sup.sock"

# Config related with the supervised process.
[program]
# Config related with process.
[program.process]
# Path to an executable, which would spawn the supervised process.
path = "./test.sh"
# Arguments to the supervised process.
args = []
# Working directory of the supervised process. Current directory by default.
workDir = "./"
# Start the process as Sup goes up. False by default.
autoStart = true
# Sup waits 'startSeconds' after each start to avoid the process restarts too rapidly.
startSeconds = 3
# How to react when the supervised process went down. One of 'on-failure', 'always', 'none'. 'on-failure' by default.
restartStrategy = "on-failure"
# Environment variables to the supervised process.
[program.process.envs]
ENV_VAR1 = "val1"
ENV_VAR2 = "val2"

# Config related with log. Log will be acquired from stdout and stderr only.
[program.log]
# Path where to save the current un-rotated log. Using basename of the supervised process by default.
path = "./test.log"
# Whether the rotated log files should be compressed with gzip, no compression by default.
compress = false
# Whether the gzipped backups would be merged or not, no merging by default.
mergeCompressed = false
# Maximum days to retain old log files based on the UTC time encoded in their filename.
maxDays = 30
# Maximum number of old log files to retain. Retaining all old log files by default.
maxBackups = 32
# Maximum size in MiB of the log file before it gets rotated. 128 MiB by default.
maxSize = 128